name: EduSource Frontend CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Note: 'actions/setup-node' is the standard repo
        with:
          node-version: 22  # Update this to 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Check for Linting Errors
        run: npm run lint 

      - name: Build Project
        run: npm run build 
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}